### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by keithmancuso** [SalesforceFoundation/CumulusReports#2]
We are getting an error when we try to install this but cant for the life of me figure out why?

I see this in the deployment status area, any ideas?

<img width="1181" alt="deployment_details___salesforce_-_enterprise_edition" src="https://user-images.githubusercontent.com/275913/28392297-55c5284e-6caf-11e7-9ae4-c777e213d231.png">

**Comment by judisohn** [comment]
@keithmancuso That is a joined report. You are in an older org where the new (well it was new years ago) report functionality for Joined reports was not enabled. Go to Setup > Reports & Dashboards > Reports and Dashboards Settings and click the 'Enable' button. Then try deploying again.

**Comment by keithmancuso** [comment]
Ohh jeez, sorry to have bugged you with that, I totally see that now and its in your existing documentation to check that but I didn't realize how old they were so i just assumed that was already enabled.

Thanks for your quick reply and the fix, after I did that it installed just fine!
